name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2
    - name: Download submodules
      run: ./buildutils/clone-submodules.sh
    - name: Update submodules
      run: ./buildutils/update-submodules.sh
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Prepare to sign apk
      run: mkdir app/build/outputs/apk/release && cp app/build/outputs/apk/app-release-unsigned.apk app/build/outputs/apk/release/
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release/
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: android
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Copy signed apk to the right place
      run: cp $SIGNED_RELEASE_FILE app/build/outputs/apk/app-final.apk
    - name: Upload apks (1/2)
      uses: actions/upload-artifact@v2
      with:
        name: other_apks
        path: app/build/outputs/apk/
    - name: Upload apks (2/2)
      uses: actions/upload-artifact@v2
      with:
        name: app-final.apk
        path: app/build/outputs/apk/app-final.apk
    - name: send custom message
      env:
        TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: | 
        sudo apt-get update
        sudo apt-get install -y curl
        curl -s "https://api.telegram.org/bot$TOKEN/sendMessage?chat_id=-1001367413201&text=New app build is ready. Check it here https://github.com/Android-Boot-Manager/App/actions/runs/$GITHUB_RUN_ID"
