name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download submodules
      run: ./buildutils/clone-submodules.sh
    - name: Update submodules
      run: ./buildutils/update-submodules.sh
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Prepare to sign apk
      run: mkdir app/build/outputs/apk/release && cp app/build/outputs/apk/app-release-unsigned.apk app/build/outputs/apk/release/
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/app-release-unsigned.apk
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Copy signed apk to the right place
      run: cp $SIGNED_RELEASE_FILE app/build/outputs/apk/app-final.apk
    - uses: actions/upload-artifact@v1
      with:
        name: apks
        path: app/build/outputs/apk/
